package hibernate_fabrica;
// Generated 28-ene-2019 13:30:03 by Hibernate Tools 4.3.1



/**
 * Seccion generated by hbm2java
 */
public class Seccion  implements java.io.Serializable {


     private Integer idSeccion;
     private String nombre;
     private int NTrabajadores;
     private String trabajador;

    public Seccion() {
    }

    public Seccion(String nombre, int NTrabajadores, String trabajador) {
       this.nombre = nombre;
       this.NTrabajadores = NTrabajadores;
       this.trabajador = trabajador;
    }
   
    public Integer getIdSeccion() {
        return this.idSeccion;
    }
    
    public void setIdSeccion(Integer idSeccion) {
        this.idSeccion = idSeccion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNTrabajadores() {
        return this.NTrabajadores;
    }
    
    public void setNTrabajadores(int NTrabajadores) {
        this.NTrabajadores = NTrabajadores;
    }
    public String getTrabajador() {
        return this.trabajador;
    }
    
    public void setTrabajador(String trabajador) {
        this.trabajador = trabajador;
    }

    void setSeccion(String nextLine) {
        
    }

    String getSeccion() {
         return null;
        
    }




}


